databaseType: "sqlite3"
databaseHost: "plankton.db"
concurrencyLimit: 4
ResultChannelSize: 1000

databaseType: "postgres"
databaseHost: "host=127.0.0.1 port=5432 user=postgres dbname=mytestdb password=mysecretpassword sslmode=disable")
