DatabaseType: "sqlite3"
DatabaseHost: "plankton.db"
ConcurrencyLimit: 4
ResultChannelSize: 1000
LoggingDirectory: "/var/log/plankton/"

DatabaseType: "postgres"
DatabaseHost: "host=127.0.0.1 port=5432 user=postgres dbname=mytestdb password=mysecretpassword sslmode=disable")
